# Generated by Django 2.0.3 on 2019-05-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='toppings',
            new_name='topping',
        ),
    ]
